import type { Metadata } from 'next'

import './globals.css'
import './theme.css'
import { NavigationContextProvider } from '@/components/Navigation/NavigationContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body className="light">
        <NavigationContextProvider>{children}</NavigationContextProvider>
      </body>
    </html>
  )
}
